### PR TITLE
Auto-generate sidebar archive dates

### PR DESCRIPTION
**Pull request by ksnavely**
This PR should auto-generate dates in the sidebar area.

### CODE REVIEW

**Comment by ksnavely** [comment]
Looks good in staging.

**Comment by evansde77** [comment]
+1 may be able to save some SLOC with the arrow.Range stuff though

**Comment by ksnavely** [comment]
Ah dude, that's a great suggestion, thanks!

**Comment by ksnavely** [comment]
Heh, it was the same LOC but we don't have to use my goofy logic so that's good. :+1:

**Pull request merged**
